command:
  description: Send Rainbird command to controller
  fields:
    id:
      description: Identification of the command to pair with response event
      example: myCallToIrrigateZone1
    host:
      description: Hostname of already configured controller
      example: rainbird.home
    command:
      description: Command to call
      example: CommandSupport
    parameters:
      description: Parameters of the command
      example: |-
        commandToTest: '30'
