start_irrigation:
  description: Start irrigation
  fields:
    zone:
      description: Zone to irrigate
      example: 1
    delay:
      description: Time to irrigate
      example: '00:03:00'
set_rain_delay:
  description: ČEZ HDO.
  fields:
    delay:
      description: Code
      example: '00:02:00'
