command:
  description: Send Rainbird command to controller
  fields:
    id:
      description: Identification of the command to pair with response event
      example: myCallToIrrigateZone1
    command:
      description: Command to call
      example: CommandSupportRequest
    parameters:
      description: Parameters of the command
      example: |-
        commandToTest: '30'
